# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Document/FPGA Code/FMC125/FMC125.srcs/sources_1/ip/pll_50Mto160M/pll_50Mto160M.xci
# IP: The module: 'pll_50Mto160M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Document/FPGA Code/FMC125/FMC125.srcs/sources_1/ip/pll_50Mto160M/pll_50Mto160M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_50Mto160M'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/Document/FPGA Code/FMC125/FMC125.srcs/sources_1/ip/pll_50Mto160M/pll_50Mto160M.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_50Mto160M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/Document/FPGA Code/FMC125/FMC125.srcs/sources_1/ip/pll_50Mto160M/pll_50Mto160M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_50Mto160M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: d:/Document/FPGA Code/FMC125/FMC125.srcs/sources_1/ip/pll_50Mto160M/pll_50Mto160M.xci
# IP: The module: 'pll_50Mto160M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Document/FPGA Code/FMC125/FMC125.srcs/sources_1/ip/pll_50Mto160M/pll_50Mto160M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_50Mto160M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/Document/FPGA Code/FMC125/FMC125.srcs/sources_1/ip/pll_50Mto160M/pll_50Mto160M.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_50Mto160M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/Document/FPGA Code/FMC125/FMC125.srcs/sources_1/ip/pll_50Mto160M/pll_50Mto160M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_50Mto160M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
